### ISSUE TITLE
PyPI rights for release

### ISSUE THREAD

**Issue by icemac** [collective/collective.soupstrainer#5]
Could we get rights on PyPI to make releases by ourselves?
Our names there are:
* sallner
* icemac

**Comment by icemac** [comment]
@fschulze Ping.

**Comment by icemac** [comment]
@fschulze If you do not want to give away the PyPI rights, could you please make a release yourself?

**Comment by fschulze** [comment]
Didn't see the notification about this. I added you to pypi.
